# Generated by Django 4.0.1 on 2022-02-11 07:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEtudiant', models.CharField(max_length=50)),
                ('postnomEtu', models.CharField(max_length=50)),
                ('prenomEtud', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('lieuNaissaince', models.CharField(max_length=50)),
                ('dateNaissance', models.DateTimeField(verbose_name=datetime.datetime(2022, 2, 11, 8, 13, 56, 781869))),
                ('adresseDomicile', models.TextField()),
                ('nomTuteur', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPromotion', models.CharField(max_length=50)),
                ('filiere', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(verbose_name=datetime.datetime(2022, 2, 11, 8, 13, 56, 781869))),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montantPayer', models.IntegerField()),
                ('designation', models.TextField()),
                ('createdAt', models.DateTimeField(verbose_name=datetime.datetime(2022, 2, 11, 8, 13, 56, 781869))),
                ('nomEtudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.etudiant')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.promotion')),
            ],
        ),
    ]
